### ISSUE TITLE
Suggest repackaging.

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen1-theme#1]
Could this theme and bunsen1-dark-theme perhaps be repackaged together in a package named "bunsen-themes", eventually containing a small collection? Themes are fairly small and it wouldn't be a large download to have them all together.

**Comment by capn-damo** [comment]
There is also Bunsen1-Blue - a theme collection would be nice.

The Bunsen1 theme in the netinstall isn't the same as hhh's Bunsen1 theme that I'm using. Is it an older version? hhh modified the original to make highlighted buttons more visible, which I find much more useable.

EDIT: I've just tried the Bunsen1 theme from github, and it is the old version :(

**Comment by 2ion** [comment]
I don't know what exactly you are proposing: Are you suggesting to use a common *source* package for all Bunsen* theme stuff from which lseveral packages are going to be built, or a single package that will install All The Themes? I would be strongly in favour of doing the single-source thing instead of a catch-all package.

**Comment by hhhorb** [comment]
Sorry for being out of the loop lately, life gets in the way...

I think they're proposing the latter, a deb that installs all themes the way the 'mate-themes' package does in jessie and sid. And Damo is right that the themes in my Dropbox account are more recent than the ones here.
 
The themes I'd recommend a binary package contains would be the 3 latest themes, Bunsen1, Bunsen1-Blue and Bunsen2-Blue-Dark (and probably a matching dark one with grey instead of blue as selected_bg_color), and the original Waldorf theme with an updated GTK3 theme that matches somewhat and isn't broken.

I suggest the Waldorf theme because, although the Greybird based themes I've made have similar color schemes and use the murrine engine the way Waldorf does, when I used Waldorf a couple of weeks ago I realized the buttons are way less "flat" in Waldorf (thunar location selector if it's set to "Pathbar Style" under the view menu, for example), plus some other pretty noticeable differences.

However, can we hold off uploading any more themes to GitHub for another week or two? My only computer has bit the big one, and I'm currently waiting for a new one to arrive. I'm using a Samsung Chromebook (Exynos processor) in the meantime which, while a beautiful piece of machinery, uses an armhf processor and a retarded keyboard layout that are hampering my theming. :^P

Another reason to hold off is that we haven't decided on the default wallpaper/color scheme. If we go with a different shade of blue or another color entirely, the default themes should match that.

From my understanding of it, a source package would be the "right" way to go, but I don't know how practical it is in that I doubt many Bunsen users would know what to do with it.

**Comment by Sector11** [comment]
binaries?  Please read:  http://crunchbang.org/forums/viewtopic.php?id=39345

**Comment by johnraff** [comment]
OK binaries. I think in the world of Debian packaging "binary" is used to mean anything that is compiled from a source package, even a bunch of text files. Someone please correct me if I'm wrong.

What I'm suggesting here is in fact a "compiled" package called bunsen-themes which would contain a (small number) of recommended themes all to be installed together. One would be set in bunsen-configs by default. Themes are small and even a set of 3 or 4 would still be a small download. 
My other suggestion is to make the naming match the other packages, ie bunsen-*

I think wallpaper should come in a separate package to cater for those who want to keep their download/installsize to a minimum. As to whether wallpaper and themes packages should be built by a single *source* package or two, I have no strong opinion on that.

Wallpapers should indeed match the themes to some extent - maybe the naming should give the user a hint as to which wallpaper is expected to go with which theme. *One* theme and *one* wallpaper can be set by default in bunsen-configs, but as far as I know there is no mechanism that could tie a certain wallpaper to a certain theme, so that when the user changed theme the wallpaper would change to match.

For sure, just upload stuff to GitHub when you feel it's ready. The content is expected to be fluid for some time to come. For example, I'm making small changes to bl-welcome and pipemenus almost on a daily basis.

BTW users aren't expected to build their own .deb packages from the source packages. That's something that we will do at this end eventually, and put the debs on the repo. 
The experimental install script builds debs locally, but that's only for testing out the current content of the GitHub packages.

**Comment by 2ion** [comment]
On Tue, Mar 24, 2015 at 05:07:52PM -0700, John Crawley wrote:
> OK binaries. I think in the world of Debian packaging "binary" is used to mean
> anything that is compiled from a source package, even a bunch of text files.
> Someone please correct me if I'm wrong.

Yes, every .deb file is a binary package, see

  https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html

for clarification.

> What I'm suggesting here is in fact a "compiled" package called bunsen-themes
> which would contain a (small number) of recommended themes all to be installed
> together. One would be set in bunsen-configs by default. Themes are small and
> even a set of 3 or 4 would still be a small download.

A "bunsen-themes" package sounds alright to me. 

> My other suggestion is to make the naming match the other packages, ie
> bunsen-*

I agree.

> I think wallpaper should come in a separate package to cater for those who want
> to keep their download/installsize to a minimum. As to whether wallpaper and
> themes packages should be built by a single source package or two, I have no
> strong opinion on that.

I think we could keep them in a single source package as /themes and /wallpapers
subdirectories and build a bunsen-themes and bunsen-wallpapers package. This
would be neat.

> Wallpapers should indeed match the themes to some extent - maybe the naming
> should give the user a hint as to which wallpaper is expected to go with which
> theme. One theme and one wallpaper can be set by default in bunsen-configs,
> but as far as I know there is no mechanism that could tie a certain wallpaper
> to a certain theme, so that when the user changed theme the wallpaper would
> change to match.

I don't think we need to rename the wallpapers since aesthetics are as different
as they come. For example, I would hate to have to drop or modify @utoto's
"Velvet Noise" title for something else or mutilate the name.

> BTW users aren't expected to build their own .deb packages from the source
> packages. That's something that we will do at this end eventually, and put the
> debs on the repo.
>
> The experimental install script builds debs locally, but that's only for
> testing out the current content of the GitHub packages.

Yup.

**Comment by 2ion** [comment]
I'll get to this during this week.

**Comment by hhhorb** [comment]
Ha, good timing on my part! Can you hold off on this for another week? I haven't nailed down the lightdm theme, I want Waldorf with an updated GTK3 to be part of this package, I want to review all the themes for consistency and I want to have us decide on which accent color we'll use for the default theme, grey, blue, turquoise?

Unless it's no problem to update the package when I've done those things, in which case fire at will!

**Comment by 2ion** [comment]
Sure, no problem.

**Comment by johnraff** [comment]
@hhhorb @2ion Any progress on this?
People using the netinstall script are still getting the old stuff from bunsen1-theme atm...

**Comment by hhhorb** [comment]
Updated...
http://crunchbang.org/forums/viewtopic.php?id=39606

**Comment by 2ion** [comment]
Sorry for the belated reply – I'll get to this next weekend at the latest.

**Comment by 2ion** [comment]
I have uploaded the bunsen-themes package! You can grab a build here: https://bitbucket.org/2ion/bunsen-builds/downloads

Question: I think I am going to take my repo https://github.com/2ion/bunsen-artwork-prerelease and make it into bunsen-wallpapers. I grabbed the wallpapers there from an assortment posted by @capn-damo on the forums weeks ago and have since kind of lost track of whether improved versions of the wallpapers have been posted – does somebody here know about this?

**Comment by johnraff** [comment]
**Bunsen-images** has already been created with possibly the same set of image files. I Debianized it last week, and later put all the images in a tarball to save some download time. I'm not 100% sure if that was the right thing to do, but it could be reversed.

**Comment by johnraff** [comment]
The netinstall script should now install **bunsen-themes** and set the new default theme "Bunsen" in all the appropriate places.

**Comment by capn-damo** [comment]
bunsen-images has all the artwork.

**Comment by 2ion** [comment]
Cool, ACK.

**Comment by 2ion** [comment]
I suppose this can be closed then, further business will be with bunsen-images.
